(()=>{var S=["sisters","parent","children","descendants","farm"];var I={sisters:"Sisters",parent:"Parent",children:"Children",descendants:"Descendants",farm:"Farm",neighbourhood:"Neighbourhood",snapshot:"Snapshot"},A=t=>(t||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\*(.+?)\*/g,"<i>$1</i>"),H=t=>{let n=Math.floor(t/1e3),e=1.9,s="a minute ago";return n>e*60&&(s=`${Math.round(n/60)} minutes ago`),n>e*3600&&(s=`${Math.round(n/3600)} hours ago`),n>e*86400&&(s=`${Math.round(n/86400)} days ago`),n>e*604800&&(s=`${Math.round(n/604800)} weeks ago`),n>e*2592e3&&(s=`${Math.round(n/2592e3)} months ago`),n>e*31536e3&&(s=`${Math.round(n/31536e3)} years ago`),s},O=t=>{if(!t)return"";let n=t.map(e=>e.date).filter(e=>typeof e=="number");return n.length?H(Date.now()-Math.max(...n)):""},C=()=>[80,"80","",null].includes(location.port)?"":`:${location.port}`,T={FAMILY:["parent","sisters"],SISTERS:"sisters",PARENT:"parent",CHILDREN:"children",DESCENDANTS:"descendants",FARM:"farm",NEIGHBOURHOOD:"neighbourhood",NEIGHBORHOOD:"neighbourhood",SNAPSHOT:"snapshot"},E=(t,n)=>(t||"").split(`
`).some(e=>e.trim().split(/\s+/)[0].replace(/:$/,"").toUpperCase()===n),K=t=>{let n=[];for(let e of(t||"").split(`
`)){let s=e.trim();if(!s)continue;let p=s.split(/\s+/)[0].replace(/:$/,"").toUpperCase(),d=T[p];if(d)for(let m of[].concat(d))n.includes(m)||n.push(m)}return n.length?n:["sisters"]},L=t=>t.endsWith("."+location.hostname)?t.slice(0,-(location.hostname.length+1)):t.split(".")[0],P=(t,n,e)=>{let s=C(),p=L(t),d=`<img class=remote title="${t}${s}" src="//${t}${s}/favicon.png" data-site="${t}${s}" data-slug=welcome-visitors>`;return`<tr><td align=right>${p} ${d}<td data-site="${t}${s}">${n} pages ${O(e)}`},z=(t,n)=>`<p class=caption><b>${I[t]}</b></p><table width=100% class=family-${t}>${n.join(`
`)}</table>`,U=(t,n)=>{let e=C(),s=K(n.text),p=E(n.text,"FREEZE"),d=E(n.text,"FORK"),m=E(n.text,"TWIN"),N=d||m,b=(t.closest(".page").attr("id")||"").split("_rev")[0],x={},M=o=>{let l=wiki.neighborhood[o]?.sitemap;return Array.isArray(l)&&l.some(h=>h.slug===b)},w={},D=(o,l)=>{o in w||!M(o)||(w[o]=void 0,wiki.site(o).get(`${b}.json`,(h,y)=>{w[o]=!h&&Array.isArray(y?.journal)&&y.journal.some(u=>u?.type==="fork"),l()}))},F=o=>d?w[o]===!0:M(o);if(t.closest(".page").hasClass("remote")){t.html(`<div class=family style="background-color:#eee;padding:15px"><center>${A(n.text)}<p class=caption>Family is only available when viewed on a page's home wiki.</p></div>`);return}t.html(`<div class=family style="background-color:#eee;padding:15px"><center>${A(n.text)}<p class=caption>gathering\u2026</p><div class=groups></div></div>`);let R=o=>{let l={};for(let i of s)if(S.includes(i)){let r=o[i]||[];x[i]=r.map(a=>a.site),l[i]=r.map(a=>a.site+e);for(let a of l[i])wiki.neighborhoodObject.registerNeighbor(a)}else{let r=Object.keys(wiki.neighborhood);x[i]=r,l[i]=r}let h=()=>{let i=new Set,r=[];for(let a of s)for(let c of l[a])d&&D(c,u),!(i.has(c)||!F(c))&&(i.add(c),r.push(`<img class="remote" src="${wiki.site(c).flag()}" title="${c}" data-site="${c}" data-slug="${b}">`));return r},y=()=>{let i=[];for(let r of s){let a=l[r].map(f=>{let k=e&&f.endsWith(e)?f.slice(0,-e.length):f,g=wiki.neighborhood[f]?.sitemap;return P(k,g?g.length:0,g)}),c=S.includes(r)?"<tr><td><i>none</i>":"<tr><td><i>empty</i>";i.push(z(r,a.length?a:[c]))}return i.join(`
`)},u=()=>{if(N){let i=h();t.find(".groups").html(i.join(" ")),t.find(".caption").first().text(i.length?"":d?"no family forks yet":"no family twins yet");return}t.find(".groups").html(y()),t.find(".caption").first().text("just updated")};if(u(),p){let i=location.hostname.split(".")[0],r=$('<button class=family-freeze style="margin-top:8px;padding:4px 12px;cursor:pointer;font-size:13px">\u2744 Freeze</button>');r.on("click",()=>{let a=()=>Math.floor(Math.random()*0xffffffffffff).toString(16).padStart(12,"0"),c=[{type:"markdown",id:a(),text:`# ${i} Family`}];for(let k of s){let g=x[k]||[];c.push({type:"roster",id:a(),text:`${I[k]} Wikis

${g.join(`
`)||"(none)"}`})}let f=wiki.newPage({title:`${i} Family`,story:c});wiki.showResult(f,{$page:t.parents(".page")})}),t.find(".family").append(r)}$("body").on("new-neighbor-done",(i,r)=>{if(N)return u();let a=t.find(`td[data-site="${r}"]`);if(!a.length)return;let c=wiki.neighborhood[r]?.sitemap;c&&a.text(`${c.length} pages ${O(c)}`)})},j=s.filter(o=>S.includes(o));if(j.length===0){R({});return}fetch(`/plugin/family/roll?kinds=${encodeURIComponent(j.join(","))}`).then(o=>{if(!o.ok){let l=new Error(`HTTP ${o.status}`);throw l.status=o.status,l}return o.json()}).then(o=>R(o.groups||{})).catch(o=>{let l=o&&o.status===404?"family server not loaded \u2014 the host wiki may need a restart or a newer wiki-server / Node":"server error";t.find(".caption").first().text(l)})},W=(t,n)=>{t.dblclick(()=>wiki.textEditor(t,n))};typeof window<"u"&&(window.plugins=window.plugins||{},window.plugins.family={emit:U,bind:W});})();
//# sourceMappingURL=family.js.map
