(()=>{var w=["sisters","parent","children","descendants","farm"];var N={sisters:"Sisters",parent:"Parent",children:"Children",descendants:"Descendants",farm:"Farm",neighbourhood:"Neighbourhood",snapshot:"Snapshot"},S=t=>(t||"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\*(.+?)\*/g,"<i>$1</i>"),O=t=>{let e=Math.floor(t/1e3),n=1.9,o="a minute ago";return e>n*60&&(o=`${Math.round(e/60)} minutes ago`),e>n*3600&&(o=`${Math.round(e/3600)} hours ago`),e>n*86400&&(o=`${Math.round(e/86400)} days ago`),e>n*604800&&(o=`${Math.round(e/604800)} weeks ago`),e>n*2592e3&&(o=`${Math.round(e/2592e3)} months ago`),e>n*31536e3&&(o=`${Math.round(e/31536e3)} years ago`),o},M=t=>{if(!t)return"";let e=t.map(n=>n.date).filter(n=>typeof n=="number");return e.length?O(Date.now()-Math.max(...e)):""},F=()=>[80,"80","",null].includes(location.port)?"":`:${location.port}`,C={FAMILY:["parent","sisters"],SISTERS:"sisters",PARENT:"parent",CHILDREN:"children",DESCENDANTS:"descendants",FARM:"farm",NEIGHBOURHOOD:"neighbourhood",NEIGHBORHOOD:"neighbourhood",SNAPSHOT:"snapshot"},D=t=>(t||"").split(`
`).some(e=>e.trim().split(/\s+/)[0].replace(/:$/,"").toUpperCase()==="FREEZE"),I=t=>(t||"").split(`
`).some(e=>e.trim().split(/\s+/)[0].replace(/:$/,"").toUpperCase()==="FORK"),A=t=>{let e=[];for(let n of(t||"").split(`
`)){let o=n.trim();if(!o)continue;let d=o.split(/\s+/)[0].replace(/:$/,"").toUpperCase(),l=C[d];if(l)for(let f of[].concat(l))e.includes(f)||e.push(f)}return e.length?e:["sisters"]},H=t=>t.endsWith("."+location.hostname)?t.slice(0,-(location.hostname.length+1)):t.split(".")[0],j=(t,e,n,o="welcome-visitors")=>{let d=F(),l=H(t),f=`<img class=remote title="${t}${d}" src="//${t}${d}/favicon.png" data-site="${t}${d}" data-slug="${o}">`;return`<tr><td align=right>${l} ${f}<td data-site="${t}${d}">${e} pages ${M(n)}`},T=(t,e)=>`<p class=caption><b>${N[t]}</b></p><table width=100% class=family-${t}>${e.join(`
`)}</table>`,v=(t,e)=>{let n=F(),o=A(e.text),d=D(e.text),l=I(e.text),f=t.closest(".page").data("key"),u={},R=r=>{let c=wiki.neighborhood[r]?.sitemap;return Array.isArray(c)&&c.some(g=>g.slug===f)};if(t.closest(".page").hasClass("remote")){t.html(`<div class=family style="background-color:#eee;padding:15px"><center>${S(e.text)}<p class=caption>Family is only available when viewed on a page's home wiki.</p></div>`);return}t.html(`<div class=family style="background-color:#eee;padding:15px"><center>${S(e.text)}<p class=caption>gathering\u2026</p><div class=groups></div></div>`);let b=r=>{let c={};for(let s of o)if(w.includes(s)){let i=r[s]||[];u[s]=i.map(a=>a.site),c[s]=i.map(a=>a.site+n);for(let a of c[s])wiki.neighborhoodObject.registerNeighbor(a)}else{let i=Object.keys(wiki.neighborhood);u[s]=i,c[s]=i}let g=()=>{let s=[];for(let i of o){let a=l?c[i].filter(R):c[i];if(l&&a.length===0)continue;let p=a.map(h=>{let y=n&&h.endsWith(n)?h.slice(0,-n.length):h,k=wiki.neighborhood[h]?.sitemap;return j(y,k?k.length:0,k,l?f:"welcome-visitors")}),m=w.includes(i)?"<tr><td><i>none</i>":"<tr><td><i>empty</i>";s.push(T(i,p.length?p:[m]))}return s.join(`
`)},E=()=>{let s=g();t.find(".groups").html(s),t.find(".caption").first().text(l?s?"forks in your family":"no family forks yet":"just updated")};if(E(),d){let s=location.hostname.split(".")[0],i=$('<button class=family-freeze style="margin-top:8px;padding:4px 12px;cursor:pointer;font-size:13px">\u2744 Freeze</button>');i.on("click",()=>{let a=()=>Math.floor(Math.random()*0xffffffffffff).toString(16).padStart(12,"0"),p=[{type:"markdown",id:a(),text:`# ${s} Family`}];for(let h of o){let y=u[h]||[];p.push({type:"roster",id:a(),text:`${N[h]} Wikis

${y.join(`
`)||"(none)"}`})}let m=wiki.newPage({title:`${s} Family`,story:p});wiki.showResult(m,{$page:t.parents(".page")})}),t.find(".family").append(i)}$("body").on("new-neighbor-done",(s,i)=>{if(l)return E();let a=t.find(`td[data-site="${i}"]`);if(!a.length)return;let p=wiki.neighborhood[i]?.sitemap;p&&a.text(`${p.length} pages ${M(p)}`)})},x=o.filter(r=>w.includes(r));if(x.length===0){b({});return}fetch(`/plugin/family/roll?kinds=${encodeURIComponent(x.join(","))}`).then(r=>{if(!r.ok){let c=new Error(`HTTP ${r.status}`);throw c.status=r.status,c}return r.json()}).then(r=>b(r.groups||{})).catch(r=>{let c=r&&r.status===404?"family server not loaded \u2014 the host wiki may need a restart or a newer wiki-server / Node":"server error";t.find(".caption").first().text(c)})},z=(t,e)=>{t.dblclick(()=>wiki.textEditor(t,e))};typeof window<"u"&&(window.plugins=window.plugins||{},window.plugins.family={emit:v,bind:z});})();
//# sourceMappingURL=family.js.map
